blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blog, name='all_blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('products/', include('products.urls')),
    path('todo/', include('todo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
]

todo/urls.py
from django.urls import path

from todo import views

app_name = 'todo'

urlpatterns = [
    path('', views.hometodo, name='hometodo'),
    path('create/', views.createtodo, name='createtodo'),
    path('current/', views.currenttodos, name='currenttodos'),
    path('completed/', views.completedtodos, name='completedtodos'),
    path('todo/<int:todo_pk>', views.viewtodo, name='viewtodo'),
    path('todo/<int:todo_pk>/complete', views.completetodo, name='completetodo'),
    path('todo/<int:todo_pk>/delete', views.deletetodo, name='deletetodo'),

    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
]

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

products/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    stock = models.IntegerField()
    image_url = models.CharField(max_length=2083)


class Offer(models.Model):
    code = models.CharField(max_length=10)
    description = models.CharField(max_length=255)
    discouunt = models.FloatField()

todo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class ToDo(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import ToDo


class ToDoForm(ModelForm):
    class Meta:
        model = ToDo
        fields = ['title', 'memo', 'important']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.


def all_blog(request):
    blogs = Blog.objects.order_by('-date')[:5]
    #blogs = Blog.objects.all()
    return render(request, 'blog/all_blog.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

products/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Product
# Create your views here.


def index(request):
    products = Product.objects.all()
    return render(request, 'index.html',
                  {'products': products})


def new(request):
    return HttpResponse("This is New page")

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import ToDoForm
from .models import ToDo
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.


def hometodo(request):
    return render(request, 'todo/home.html')


def signupuser(request):
    if request.method == 'GET':
        return render(request, 'todo/signupuser.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('todo:currenttodos')
            except IntegrityError:
                return render(request, 'todo/signupuser.html', {'form': UserCreationForm(), 'error': 'That Username has already been taken, Please try a new one..!'})
        else:
            # tell user that passwords didn't match
            return render(request, 'todo/signupuser.html', {'form': UserCreationForm(), 'error': 'Passwords didnt match!'})


def loginuser(request):
    if request.method == 'GET':
        return render(request, 'todo/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'todo/loginuser.html', {'form': AuthenticationForm(), 'error': 'Username or Password is not Correct!'})
        else:
            login(request, user)
            return redirect('todo:currenttodos')


@login_required
def logoutuser(request):
    if request.method == "POST":
        logout(request)
        return redirect('todo:hometodo')


@login_required
def createtodo(request):
    if request.method == 'GET':
        return render(request, 'todo/createtodo.html', {'form': ToDoForm()})
    else:
        try:
            form = ToDoForm(request.POST)
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request, 'todo/createtodo.html', {'form': ToDoForm(), 'error': 'Data in Bad Format, Try Again'})


@login_required
def currenttodos(request):
    todos = ToDo.objects.filter(user=request.user, datecompleted__isnull=True)
    return render(request, 'todo/currenttodos.html', {'todos': todos})


@login_required
def completedtodos(request):
    todos = ToDo.objects.filter(
        user=request.user, datecompleted__isnull=False).order_by('-datecompleted')
    return render(request, 'todo/completedtodos.html', {'todos': todos})


@login_required
def viewtodo(request, todo_pk):
    todo = get_object_or_404(ToDo, pk=todo_pk, user=request.user)
    if request.method == 'GET':
        form = ToDoForm(instance=todo)
        return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form})
    else:
        try:
            form = ToDoForm(request.POST, instance=todo)
            form.save()
            return redirect('todo:currenttodos')
        except ValueError:
            return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form, 'error': 'Bad data format..'})


@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(ToDo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.datecompleted = timezone.now()
        todo.save()
        return redirect('todo:currenttodos')


@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(ToDo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('todo:currenttodos')

blog/templates/blog/all_blog.html
{% extends "portfolio/base.html" %} {% load static %} {% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">
  Fayaz has written {{ blogs.count }} blog{{ blogs.count|pluralize }}
</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %} {% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

    <link
      href="https://fonts.googleapis.com/css?family=Lato&display=swap"
      rel="stylesheet"
    />

    <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

    <title>Rana Fayaz</title>
  </head>

  <body>
    <nav id="topNav" class="navbar navbar-expand-md navbar-light bg-warning">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
          <span>Rana Fayaz</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="px-2">
              
              <a role="button" href="{% url 'todo:hometodo' %}" class="btn btn-success">ToDoWoo</a>
            </li>
            <li class="px-2">
              
              <a role="button" href="{% url 'products:index' %}" class="btn btn-primary">Store</a>
            </li>
            <li class="nav-item">
              <a class="nav-link font-weight-bold text-light px-2" href="{% static "portfolio/resume.pdf" %}">Resume</a>
            </li>
            <li class="nav-item">
              <a class="nav-link font-weight-bold text-light px-2" href="https://www.linkedin.com/in/rana-fayaz-661a9996/" target="_blank">LinkedIn</a>
            </li>
            <li class="nav-item">
              <a class="nav-link font-weight-bold text-light px-2" href="https://www.instagram.com/fazzi01/" target="_blank">Instagram</a>
            </li>
            <li class="nav-item">
              <a class="nav-link font-weight-bold text-light px-2" href="https://twitter.com/Fazzi01" target="_blank">Twitter</a>
            </li>
            <li>
              <a role="button" href="{% url 'blog:all_blog' %}" class="btn btn-primary">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <footer class="bg-dark text-white mt-5 p-5">
      <div class="container">
          <p class="lead text-center">Copyright &copy 2020 Rana Fayaz</p>
      </div>
  </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

portfolio/templates/portfolio/base2.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Rana's Store</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">The Fruit Shop</a>
      </nav>
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %} {% load static %} {% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/fayaz.jpg' %}" class="img-fluid" />
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">
      😎 Rana Fayaz is Commander-in-Chief at Fazzi's Blog & Portfolio and lives in Lahore
      Pakistan 😊
    </h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr />
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">
    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2" />
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2" />
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>
  </div>
  {% endfor %}
</div>

{% endblock %}

products/templates/index.html
{% extends 'portfolio/base.html' %} {% block content %}
<h1>Products</h1>
<div class="row">
  {% for product in products %}
  <div class="col">
    <div class="card" style="width: 18rem;">
      <img src="{{ product.image_url }}" class="card-img-top" alt="..." />
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">Rs. {{ product.price }} / Kg</p>
        <a href="#" class="btn btn-primary">Add to Cart</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <link rel="icon" type="image/png" href="{% static 'todo/logo.png' %}" />
    <title>Todo Woo</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-warning">
      <div class="container">
        <a class="navbar-brand" href="{% url 'todo:hometodo' %}">
          <img
            src="{% static 'todo/logo.png' %}"
            width="30"
            height="30"
            class="d-inline-block align-top"
          />
          <span>Todo Woo</span>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ current }}">
              <a class="nav-link" href="{% url 'todo:currenttodos' %}">Current</a>
            </li>
            <li class="nav-item {{ completed }}">
              <a class="nav-link" href="{% url 'todo:completedtodos' %}">Completed</a>
            </li>
            <li class="nav-item {{ create }}">
              <a class="nav-link" href="{% url 'todo:createtodo' %}">Create</a>
            </li>
            
          </ul>
          {% endif %}
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="#" class="navbar-brand">Welcome! {{ user.username }}</a>
              <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
              <form
                style="display: none;"
                method="POST"
                action="{% url 'todo:logoutuser' %}">
                {% csrf_token %}
                <button id="signOutBtn" type="submit">Logout</button>
              </form>
            </li>
            {% else %}
            <!-- <li class="nav-item">
              <a class="navbar-brand" href="{% url 'home' %}">Back to Site!</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:signupuser' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:loginuser' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="navbar-brand" href="{% url 'home' %}">Back to Site!</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <footer class="bg-dark text-white mt-5 p-5">
      <div class="container">
          <p class="lead text-center">Copyright &copy 2020 Rana Fayaz</p>
      </div>
  </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

todo/templates/todo/completedtodos.html
{% extends "todo/base.html" %} {% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-10">
    <h1>Completed Todos</h1>
  </div>
</div>
<div class="row justify-content-center mt-5">
  <div class="col-md-10">
    <div class="list-group">
      {% for todo in todos %}
      <a
        href="{% url 'todo:viewtodo' todo.id %}"
        class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"
        ><b>{{ todo.title }}</b> - Completed {{ todo.datecompleted|date:'M j Y H:i' }}</a>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

todo/templates/todo/currenttodos.html
{% extends "todo/base.html" %} {% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-10">
    {% if todos %}
    <h1>{{ todos.count }} Current Todo{{ todos.count|pluralize }}</h1>
    {% else %}
    <h1>Current Todos</h1>
    {% endif %}
  </div>
</div>
<div class="row justify-content-center mt-5">
  <div class="col-md-10">
    {% if todos %}
    <div class="list-group">
      {% for todo in todos %}
      <a
        href="{% url 'todo:viewtodo' todo.id %}"
        class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}">
        <b>{{ todo.title }}</b>{% if todo.memo %} - {{ todo.memo|truncatechars:30 }} {% endif %}</a>
      {% endfor %}
    </div>
    {% else %}
    <div class="text-center">
      <h2>Looks like you don't have any todos! Nice work.</h2>
      <br />
      <a
        role="button"
        class="btn btn-primary"
        href="{% url 'todo:createtodo' %}">New Todo</a>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

todo/templates/todo/home.html
{% extends "todo/base.html" %} {% block content %}
<br />
<br />
<br />
<br />
<br />
<br />
<div class="row justify-content-center mt-5">
  <div class="col-md-7 text-center">
    <h1>Simply Your Todos. Woo!</h1>
    <p>
      Life is fun. But life is also busy. There's a million different things you
      could be doing. But what matters is <u>what</u> you do. We created
      <b><i>Todo Woo</i></b> to help you make sense of all of your opportunities
      and live that life that matters most to you. Your new organized life
      awaits.
    </p>
    <a
      role="button"
      class="btn btn-primary btn-lg"
      href="{% url 'todo:signupuser' %}"
      >Start</a
    >
  </div>
</div>

{% endblock %}

todo/templates/todo/loginuser.html
{% extends "todo/base.html" %} {% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-5">
    <h2>Login</h2>
  </div>
</div>
<div class="row justify-content-center mt-5">
  <div class="col-md-5">
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% endif %}
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" name="username" class="form-control" id="username" />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          name="password"
          class="form-control"
          id="password"
        />
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <hr />
    <div class="text-center">
      Need an account? <a href="{% url 'todo:signupuser' %}">Sign Up here</a>
    </div>
  </div>
</div>
{% endblock %}

todo/templates/todo/signupuser.html
{% extends "todo/base.html" %} {% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-5">
    <h2>Sign Up</h2>
  </div>
</div>
<div class="row justify-content-center mt-5">
  <div class="col-md-5">
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% endif %}
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="username">Username</label>
        <input
          type="text"
          name="username"
          class="form-control"
          id="username"
          aria-describedby="usernameHelp"
        />
        <small id="usernameHelp" class="form-text text-muted"
          >Your username must be unique. We'll let you know if someone has taken
          it already.</small
        >
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          name="password1"
          class="form-control"
          id="password1"
        />
      </div>
      <div class="form-group">
        <label for="password2">Confirm Password</label>
        <input
          type="password"
          name="password2"
          class="form-control"
          id="password2"
        />
      </div>
      <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
    <hr />
    <div class="text-center">
      Do you already have an account?
      <a href="{% url 'todo:loginuser' %}">Login here</a>
    </div>
  </div>
</div>
{% endblock %}

todo/templates/todo/viewtodo.html
{% extends "todo/base.html" %} {% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-5">
    <h2>New Todo</h2>
  </div>
</div>
<div class="row justify-content-center mt-5">
  <div class="col-md-5">
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% endif %}
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          name="title"
          class="form-control"
          id="title"
          value="{{ todo.title }}"
          required
        />
      </div>
      <div class="form-group">
        <label for="memo">Memo</label>
        <textarea name="memo" rows="5" class="form-control" id="memo">
{{ todo.memo }}</textarea
        >
      </div>
      <div class="form-group form-check">
        <input
          type="checkbox"
          name="important"
          class="form-check-input"
          id="important"
          {%
          if
          todo.important
          %}checked{%
          endif
          %}
        />
        <label class="form-check-label" for="important">Important</label>
      </div>
      <button type="submit" class="btn btn-primary">Update & Save</button>
      <button
        type="button"
        class="btn btn-success"
        onclick="$('#complete').click()"
      >
        Complete
      </button>
      <button
        type="button"
        class="btn btn-danger"
        onclick="$('#delete').click()"
      >
        Delete
      </button>
    </form>
  </div>
</div>
{% if todo.datecompleted is None %}
<form
  style="display: none;"
  method="POST"
  action="{% url 'todo:completetodo' todo.id %}"
>
  {% csrf_token %}
  <button id="complete" type="submit">Complete</button>
</form>
{% endif %}
<form
  style="display: none;"
  method="POST"
  action="{% url 'todo:deletetodo' todo.id %}"
>
  {% csrf_token %}
  <button id="delete" type="submit">Delete</button>
</form>
{% endblock %}